#!/bin/bash

if [ -z $1 ]; then
  echo "pull <service|all>"
  exit 1
fi

INITDIR=$(pwd)
TARGETDIR=$(pwd)/services/$1

if [ "$1" = "all" ]; then
  # Pull images for each service
  for DIR in $(pwd)/services/*; do
    if [ "$(basename $DIR)" != "$PROXYNAME" ]; then
      echo Pulling images for service $(basename $DIR)
      cd $DIR
      docker compose pull
      cd $INITDIR
    fi
  done
# Specified service does not exist
elif [ -d "$TARGETDIR" ]; then
  cd $TARGETDIR
  docker compose pull
  cd $INITDIR
else
  echo "Service '$1' does not exist."
fi
